# Generated by Django 5.1.1 on 2024-09-25 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('autor', models.CharField(max_length=255)),
                ('categoria', models.CharField(max_length=255)),
                ('sinopse', models.TextField()),
                ('numero_paginas', models.IntegerField()),
                ('publicadora', models.CharField(max_length=255)),
                ('data_publicacao', models.DateField()),
                ('capa', models.URLField()),
            ],
        ),
    ]
