# Generated by Django 5.1.1 on 2024-09-27 20:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0006_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='email',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
