# Generated by Django 5.1.1 on 2024-09-27 20:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0007_perfil_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='username',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
