# Generated by Django 5.1.1 on 2024-09-27 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0008_perfil_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcarrinho',
            name='capa',
            field=models.URLField(blank=True, null=True),
        ),
    ]
