# Generated by Django 5.1.1 on 2024-09-27 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0009_itemcarrinho_capa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemcarrinho',
            name='capa',
        ),
    ]
